# Generated by Django 2.1 on 2019-11-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BatchNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=5)),
                ('course_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fee', models.CharField(max_length=255)),
                ('batch_number_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.BatchNumber')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CreditHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_room', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.BatchNumber')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Course')),
                ('lecture_room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.LectureRoom')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_day_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleDay'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_time_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleTime'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.CourseType'),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hour_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.CreditHour'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='batch_number_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.BatchNumber'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='course_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Message'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule_day_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleDay'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule_time_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleTime'),
        ),
    ]
