# Generated by Django 2.1.5 on 2019-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_announcement_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credithour',
            name='credit_hour',
            field=models.CharField(max_length=255),
        ),
    ]
